# Generated by Django 4.1.3 on 2023-05-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpoem',
            old_name='slug',
            new_name='poem_slug',
        ),
    ]
