# Generated by Django 4.1.3 on 2023-05-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_slug_postpoem_poem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpoem',
            name='post_overview',
            field=models.TextField(max_length=500),
        ),
    ]
