# Generated by Django 4.1.3 on 2023-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_poststory'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststory',
            name='author_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
